In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [5]:
df =pd.read_csv('student_data.csv')

In [6]:
df = df.drop_duplicates()

In [7]:
selected_columns = [
    'studytime',
    'failures',
    'absences',
    'age',
    'traveltime',
    'famrel',
    'freetime',
    'goout',
    'G1',
    'G2',
    'G3'
    
]
df = df[selected_columns]

In [8]:
df

,studytime,failures,absences,age,traveltime,famrel,freetime,goout,G1,G2,G3
0,2,0,6,18,2,4,3,4,5,6,6
1,2,0,4,17,1,5,3,3,5,5,6
2,2,3,10,15,1,4,3,2,7,8,10
3,3,0,2,15,1,3,2,2,15,14,15
4,2,0,4,16,1,4,3,2,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...
390,2,2,11,20,1,5,5,4,9,9,9
391,1,0,3,17,2,2,4,5,14,16,16
392,1,3,3,21,1,5,5,3,10,8,7
393,1,0,0,18,3,4,4,1,11,12,10
394,1,0,5,19,1,3,2,3,8,9,9

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
x = df[['studytime','failures','absences','age','traveltime','famrel','freetime','goout',
 'G1','G2']]
y = df['G3']

In [12]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [13]:
df.head()

,studytime,failures,absences,age,traveltime,famrel,freetime,goout,G1,G2,G3
0,2,0,6,18,2,4,3,4,5,6,6
1,2,0,4,17,1,5,3,3,5,5,6
2,2,3,10,15,1,4,3,2,7,8,10
3,3,0,2,15,1,3,2,2,15,14,15
4,2,0,4,16,1,4,3,2,6,10,10

In [1]:
from sklearn.metrics import confusion_matrix

y_true = [1,1,1,1,0,0,0,0]
y_pred = [1,1,0,1,0,1,0,0]

cm = confusion_matrix(y_true, y_pred)

print(cm)

[[3 1]
 [1 3]]